config/routes.rb
Rails.application.routes.draw do
  
  root to: "dashboard#index"
  devise_for :users
  
  resources :seed_fork_users
  resources :recipients
  resources :donors
  resources :foods
  
  get 'dashboard/index'
  get 'dashboard/project'
  get 'dashboard/charter'
  get 'dashboard/userstories'
  get 'dashboard/login'
  get 'dashboard/truck_inventory'
  get 'dashboard/archives'
  get 'dashboard/matches'
  

  
end

app/models/donor.rb
class Donor < ApplicationRecord
  
  #attr_accessor :username, :date_entered, :type_of_food, :weight, :quantity
  
  #def self.search(search)
  #  if search
  #    where('name LIKE ?', "%#{search}%")
  #  else
  #    scoped
  #  end
  #end
  
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_donor, only: [:show, :edit, :update, :destroy]
  
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all.order(:username, :type_of_food)
    @recipients = Recipient.order(:username)
    @usernames = Donor.select(:username).distinct.order(:username)
    @farmer = Donor.where("delivered = 'no' and pickup_name IS NULL").order(:username, :type_of_food)
   
    #@search_farmers = Donor.search(params[:search]).order(sort_column + " " + sort_direction)
  end
 
  
  # GET /donors/1
  # GET /donors/1.json
  def show
    #@donors = Donor.find(params[:id])
    #@donors = Donor.all
  end
  
  # GET /donors/new
  def new
    @donor = Donor.new
  end
  
  # GET /donors/1/edit
  def edit
  end
  
  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(donor_params)

    respond_to do |format|
      if @donor.save
        #format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.html { redirect_to donors_url, notice: 'Produce was successfully created.' }
        format.json { render :show, status: :created, location: @donor }
      else
        format.html { render :new }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /donors/1
  # PATCH/PUT /donors/1.json
  def update
    respond_to do |format|
      if @donor.update(donor_params)
        #format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.html { redirect_to donors_url, notice: 'Produce was successfully updated.' }
        format.json { render :show, status: :ok, location: @donor }
      else
        format.html { render :edit }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_url, notice: 'Produce was successfully Deleted.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donor
      #[] I DONT KNOW WHY THIS IS THROWING AN ERROR: "Couldn't find Donor with 'id'=waltersfarm"
      @donor = Donor.find(params[:id])
      #@donor = Donor.find(params[:username])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def donor_params
      params.require(:donor).permit(:username, :date_entered, :type_of_food, :price, :quantity, :weight, :units, :pickup_name, :pickup_date, :match, :email, :phone, :user_type, :quantity, :address, :season, :delivered)
    end
    
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_modal.html.erb
<!-- MODAL -->
<% if user_signed_in? %>
  <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
  <div class="modal fade" id="donorModal" tabindex="-1" role="dialog" aria-labelledby="donModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="donModalLabel">Hello</h4>
          </div>
          <div class="modal-body" id="donModalBody">
            World
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<h2>Pending Produce</h2>

<!--FARMERS/PANTRIES CAN ACCESS EACHOTHERS DATABASES-->
<!--% if current_user.farmer_role? && !current_user.pantry_role || current_user.truckdriver_role || current_user.seedforkuser_role %>
  <!--<div class = "alert alert-success alert-dismissable fade in">Valid User!
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></div>
% else %>
  <div class = "alert alert-danger alert-dismissable fade in">Invalid User!
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></div>
% end %>-->

<nav class="navbar navbar-default" role="navigation">
  <div class="nav collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
      <!--[] USED LATER FOR RESTAURANTS-->
      <!--li>%= link_to "Restaurant", foods_path %></li-->
      <li><%= link_to "Pending Produce", donors_path %></li>
      <!--li>%= link_to "Pantry", recipients_path %></li-->
      <li><%= link_to "Truck Inventory", dashboard_truck_inventory_path %></li>
    </ul>
    <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
      <ul class="nav navbar-nav">
        <!--li>%= link_to "Matches", dashboard_matches_path %></li-->
        <li><%= link_to "Archives", dashboard_archives_path %></li>
      </ul>
    <% end %>
        
    <ul class="nav navbar-nav pull-right">
      <% if current_user.farmer_role? %>
        <li><%= link_to 'New Entry', new_donor_path %></li>
      <% end %>
      <li><input type="text" id="search" placeholder="Search Farmers" style="margin:16px"></input></li>
      <!--[] CODE WORKS BUT THE FORMATTING IS OFF, AND THERE ARE EXTRA SPACES INBETWEEN EACH USERNAME-->
    	<li role="button" data-toggle="dropdown" class="dropdown nav navbar-nav" id="nav_farmer"><!--i class="glyphicon glyphicon-grain"--><%= link_to 'All Farmers' %></i></li>
      
      <ul data-toggle="dropdown" class="dropdown-menu">
        <% @usernames.each do |donor| %>
          <!--[] ONCE ONE OF THESE IS SELECTED, IT NEEDS TO CALL AN ACTIVE RECORD TO REPOPULATE THE TABLE ON THE PAGE...-->
          <li id="get_farmer"><%= link_to donor.username %></li>
        <% end %>
        
        
        <li role="presentation" class="divider"></li>
        <li><a href="#">All Farmers</li>
      </ul>
      
      
      <!--li>%= link_to 'Account', edit_user_registration_path %></li-->
      <li><%= link_to '' %></li>
      <li>
        <%= link_to edit_user_registration_path do %>
         <i class="glyphicon glyphicon-cog"></i>
        <% end %>
      </li>
    </ul>
  </div>
</nav>


<!--input type="text" id="search" placeholder="Search"></input><br><br-->


<!--% if current_user.farmer_role? && !current_user.pantry_role || current_user.truckdriver_role || current_user.seedforkuser_role %>-->
  <table class="table table-striped table-bordered" id="donorTable">
    <thead>
      <tr>
        <th onclick="sortTable(0)">Username</th>
        <th onclick="sortTable(1)">Quantity</th>
        <th onclick="sortTable(2)">Units</th>
        <th onclick="sortTable(3)">Type of Food</th>
        <!--th>Price</th-->
        <th onclick="sortTable(4)">Season</th>
        <th onclick="sortTable(5)">Date entered</th>
        <!--% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
          <th onclick="sortTable(6)">Phone</th>
          <th onclick="sortTable(7)">Email</th>
          <th onclick="sortTable(8)">Address</th>
        % end %-->
        <!--th>Match</th>
        <th onclick="sortTable(9)">Pickup date</th>
        <th onclick="sortTable(10)">Pickup name</th>
        <th onclick="sortTable(11)">Delivered</th-->
        <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    </thead>
    
    <tbody id="donorList" class="farmerList">
      <% @farmer.each do |donor| %>
        <tr>
          <td data-toggle="modal" data-target="#donorModal"><%= donor.username %></td>
          <td><%= donor.quantity %></td>
          <td><%= donor.units %></td>
          <td><%= donor.type_of_food %></td>
          <!--td>$%= donor.price %></td-->
          <td><%= donor.season %></td>
          <td><%= donor.date_entered %></td>
          <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
            <td style="display:none"><%= donor.phone %></td>
            <td style="display:none"><%= donor.email %></td>
            <td style="display:none"><%= donor.address %></td>
          <% end %>
          <!--td>%= donor.match %></td>
          <td>%= donor.pickup_date %></td>
          <td>%= donor.pickup_name %></td>
          <td>%= donor.delivered %></td-->
          
          <!--<td>%= link_to 'Show', donor %></td>-->
          <% if current_user.user_name == donor.username || current_user.truckdriver_role? || current_user.seedforkuser_role? %>
            <td><center><%= link_to 'Edit', edit_donor_path(donor), :class => "btn btn-default" %></center></td>
            <td><center><%= link_to 'Delete', donor, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %></center></td>
          <% end %>
        </tr>
        
        <!--[x] UNIVERSAL MODAL -->
        <%= render partial: "modal", locals: {zone: @zone} %>
         
      <% end %>
    </tbody>
  </table>
  
  <script type="text/javascript">
    /*=======================================*/
    /* SORT BY COLUMN - CLICK COLUMN TO SORT */
    /*=======================================*/
    function sortTable(n) {
      var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
      table = document.getElementById("donorTable");
      switching = true;
      dir = "asc"; //sorting direction: ascending
      while (switching) {
        switching = false;
        rows = table.getElementsByTagName("tr");
        //Loop through all rows except the header
        for (i = 1; i < (rows.length - 1); i++) {
          shouldSwitch = false;
          //Get the two elements you want to compare, one from current row and one from the next
          x = rows[i].getElementsByTagName("td")[n];
          y = rows[i + 1].getElementsByTagName("td")[n];
          //Check if the two rows should switch place, based on the direction, asc or desc
          if (dir == "asc") {
            if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
              shouldSwitch = true; //switch
              break;
            }
          } else if (dir == "desc") {
            if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
              shouldSwitch = true; //switch
              break;
            }
          }
        }
        if (shouldSwitch) {
          //If a switch has been marked, make the switch and mark that a switch has been done
          rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
          switching = true;
          //Each time a switch is done, increase this count by 1
          switchcount ++;      
        } else {
          //If no switching has been done AND the direction is "asc", set the direction to "desc" and run the while loop again.
          if (switchcount == 0 && dir == "asc") {
            dir = "desc";
            switching = true;
          }
        }
      }
    }
  </script>
  
<!--% end %>-->

app/views/donors/new.html.erb
<h1>New Donor</h1>

<%= render 'form', donor: @donor %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @donor.username %>
</p>

<p>
  <strong>Date entered:</strong>
  <%= @donor.date_entered %>
</p>

<p>
  <strong>Email:</strong>
  <%= @donor.email %>
</p>

<p>
  <strong>User type:</strong>
  <%= @donor.user_type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @donor.quantity %>
</p>

<p>
  <strong>Address:</strong>
  <%= @donor.address %>
</p>

<p>
  <strong>Season:</strong>
  <%= @donor.season %>
</p>

<p>
  <strong>Match:</strong>
  <%= @donor.match %>
</p>

<p>
  <strong>Pickup date:</strong>
  <%= @donor.pickup_date %>
</p>

<p>
  <strong>Pickup name:</strong>
  <%= @donor.pickup_name %>
</p>

<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>