config/routes.rb
Rails.application.routes.draw do
  
  root to: "dashboard#index"
  devise_for :users
  
  resources :seed_fork_users
  resources :recipients
  resources :donors
  resources :foods
  
  get 'dashboard/index'
  get 'dashboard/project'
  get 'dashboard/charter'
  get 'dashboard/userstories'
  get 'dashboard/login'
  get 'dashboard/truck_inventory'
  get 'dashboard/archives'
  get 'dashboard/matches'
  

  
end

app/models/recipient.rb
class Recipient < ApplicationRecord
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_recipient, only: [:show, :edit, :update, :destroy]

  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
  end

  # GET /recipients/new
  def new
    @recipient = Recipient.new
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(recipient_params)

    respond_to do |format|
      if @recipient.save
        #format.html { redirect_to @recipient, notice: 'Recipient was successfully created.' }
        format.html { redirect_to recipients_url, notice: 'Recipient was successfully created.' }
        format.json { render :show, status: :created, location: @recipient }
      else
        format.html { render :new }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipients/1
  # PATCH/PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update(recipient_params)
        #format.html { redirect_to @recipient, notice: 'Recipient was successfully updated.' }
        format.html { redirect_to recipients_url, notice: 'Recipient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipient }
      else
        format.html { render :edit }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy
    respond_to do |format|
      format.html { redirect_to recipients_url, notice: 'Recipient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient
      @recipient = Recipient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipient_params
      params.require(:recipient).permit(:username, :date_entered, :email, :user_type, :type_of_food, :quantity, :address, :phone, :match, :dropoff_date, :dropoff_name)
    end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form.html.erb
<%= form_for(recipient) do |f| %>
  <% if recipient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipient.errors.count, "error") %> prohibited this recipient from being saved:</h2>

      <ul>
      <% recipient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :username %>
    <% if current_user.pantry_role %>
      <%= f.text_field :username, value: current_user.user_name, readonly:true %>
    <% else %>
      <h4><i>Who you're updating...</i></h4>
      <%= f.text_field :username, value: recipient.username, readonly:true %>
    <% end %>
  </div>
  
  <div class="field">
    <% if current_user.pantry_role %>
      <%= f.text_field :phone, value: current_user.phone, readonly:true, hidden:true %>
    <% else %>
      <%= f.label :phone %>
      <%= f.text_field :phone, value: recipient.phone, readonly:true %>
    <% end %>
  </div>
  
  <div class="field">
    <% if current_user.pantry_role %>
      <%= f.date_field :date_entered, :value => Time.now.strftime('%Y-%m-%d'), readonly:true, hidden:true %>
      <%= f.date_field :updated_at, :value => Time.now.strftime('%Y-%m-%d'), readonly:true, hidden:true %>
    <% else %>
      <%= f.label "Date Entered" %>
      <%= f.date_field :date_entered, :value => recipient.date_entered, readonly:true %>
    <% end %>
  </div>
    
  <div class="field">
    <% if current_user.pantry_role %>
      <%= f.label :type_of_food %>
      <%= f.text_field :type_of_food, placeholder: "Carrots" %>
    <% else %>
      <%= f.label :type_of_food %>
      <%= f.text_field :type_of_food, readonly:true %>
    <% end %>
  </div>
  
  <div class="field">
    <% if current_user.pantry_role %>
      <%= f.label :quantity %>
      <%= f.number_field :quantity, placeholder: "-1 for all" %>
    <% else %>
      <%= f.label :quantity %>
      <%= f.number_field :quantity, readonly:true %>
    <% end %>
  </div>
        
  <div class="field">
    <% if current_user.pantry_role %>
      <!--%= f.label :email %>-->
      <%= f.email_field :email, value: current_user.email, readonly:true, hidden:true %>
    <% else %>
    <% end %>
  </div>
  
  <div class="field">
    <% if current_user.pantry_role %>
      <!--%= f.label :address %>-->
      <%= f.text_field :address, value: current_user.address, readonly:true, hidden:true %>
    <% else %>
    <% end %>
  </div>
  
  <div class="field">
    <% if current_user.pantry_role %>
      <!--%= f.label :user_type %>-->
      <%= f.text_field :user_type, value: current_user.type_of_user, readonly:true, hidden:true %>
    <% else %>
    <% end %>
  </div>


  <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
    <hr>
    <div style="background-color:#ffcccc; width:250px; padding-left:20px">
      <br /><h5><i style="color:red">Update Drop-off Information:</i></h5>
      <div class="field">
      <!--[] THIS NEEDS TO CALL QUERY TO DONORS TABLE TO SELECT AVAILABLE USER_NAME'S-->
        <%= f.label :match %>
        <%= f.text_field :match %>
      </div>
    
      <div class="field">
        <%= f.label :dropoff_date %>
        <%= f.date_select :dropoff_date %>
      </div>
      
      <div class="field">
        <%= f.label "Quantity Dropped Off" %>
        <%= f.number_field :quantity, placeholder: "how many off truck" %>
      </div>
    
      <div class="field">
        <%= f.label :dropoff_name %>
        <%= f.text_field :dropoff_name, :value => current_user.user_name, readonly:true %>
      </div><br />
    </div>
    <hr>
  <% end %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<h1>Editing Recipient</h1>

<%= render 'form', recipient: @recipient %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<h2>Pantry</h2>

<!--FARMERS/PANTRIES CAN ACCESS EACHOTHERS DATABASES-->
<!--% if current_user.pantry_role? && !current_user.farmer_role || current_user.truckdriver_role || current_user.seedforkuser_role %>
  <!--<div class = "alert alert-success alert-dismissable fade in">Valid User!
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></div>
% else %>
  <div class = "alert alert-danger alert-dismissable fade in">Invalid User!
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></div>
% end %>-->
    
<nav class="navbar navbar-default" role="navigation">
  <div class="nav collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
      <!--[] USED LATER FOR RESTAURANTS-->
      <li><%= link_to "Restaurant", foods_path %></li>
      <li><%= link_to "Farmer", donors_path %></li>
      <li><%= link_to "Pantry", recipients_path %></li>
      <li><%= link_to "Truck Inventory", dashboard_truck_inventory_path %></li>
    </ul>
    <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Matches", dashboard_matches_path %></li>
          <li><%= link_to "Archives", dashboard_archives_path %></li>
        </ul>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if !current_user.farmer_role? && current_user.pantry_role || current_user.truckdriver_role || current_user.seedforkuser_role %>
        <li><%= link_to 'New Entry', new_recipient_path %></li>
      <% end %>
        <!--<li>%= link_to 'Account', edit_user_registration_path %></li>-->
        <li><%= link_to edit_user_registration_path do %>
           <i class="glyphicon glyphicon-cog"></i>
        <% end %></li>
    </ul>
    
  </div>
</nav>

<!--% if !current_user.farmer_role? && current_user.pantry_role || current_user.truckdriver_role || current_user.seedforkuser_role %>-->
  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>Type of Food</th>
        <th>Quantity</th>
        <th>Date entered</th>
        <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
          <th>Phone</th>
          <th>Email</th>
          <th>Address</th>
        <% end %>
        <th>Match</th>
        <th>Dropoff date</th>
        <th>Dropoff name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @recipients.each do |recipient| %>
        <tr>
          <td><%= recipient.username %></td>
          <td><%= recipient.type_of_food %></td>
          <td><%= recipient.quantity %></td>
          <td><%= recipient.date_entered %></td>
          <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
            <td><%= recipient.phone %></td>
            <td><%= recipient.email %></td>
            <td><%= recipient.address %></td>
          <% end %>
          <td><%= recipient.match %></td>
          <td><%= recipient.dropoff_date %></td>
          <td><%= recipient.dropoff_name %></td>
          
          <!--<td>%= link_to 'Show', recipient %></td>-->
          <% if current_user.user_name == recipient.username || current_user.truckdriver_role? || current_user.seedforkuser_role? %>
            <td><%= link_to 'Edit', edit_recipient_path(recipient), :class => "btn btn-default" %></td>
            <td><%= link_to 'Delete', recipient, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<!--% end %>-->

app/views/recipients/new.html.erb
<h1>New Recipient</h1>

<%= render 'form', recipient: @recipient %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @recipient.username %>
</p>

<p>
  <strong>Date entered:</strong>
  <%= @recipient.date_entered %>
</p>

<p>
  <strong>Email:</strong>
  <%= @recipient.email %>
</p>

<p>
  <strong>User type:</strong>
  <%= @recipient.user_type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @recipient.quantity %>
</p>

<p>
  <strong>Address:</strong>
  <%= @recipient.address %>
</p>

<p>
  <strong>Match:</strong>
  <%= @recipient.match %>
</p>

<p>
  <strong>Dropoff date:</strong>
  <%= @recipient.dropoff_date %>
</p>

<p>
  <strong>Dropoff name:</strong>
  <%= @recipient.dropoff_name %>
</p>

<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Back', recipients_path %>