config/routes.rb
Rails.application.routes.draw do
  
  root to: "dashboard#index"
  devise_for :users
  
  resources :seed_fork_users
  resources :recipients
  resources :donors
  resources :foods
  
  get 'dashboard/index'
  get 'dashboard/project'
  get 'dashboard/charter'
  get 'dashboard/userstories'
  get 'dashboard/login'
  get 'dashboard/truck_inventory'
  get 'dashboard/archives'
  get 'dashboard/matches'
  

  
end

app/models/food.rb
class Food < ApplicationRecord
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:food, :amount, :frequency, :duration, :price_cap)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(food) do |f| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Add Food Request</h4>

  <div class="field">
    <%= f.label :food %>
    <%= f.text_field :food, :placeholder => "Carrots" %>
    <h6 class="small">(type of produce)</h6>
  </div>

  <div class="field">
    <%= f.label :amount %>
    $ <%= f.text_field :amount, :placeholder => "1.00" %>
    <h6 class="small">(how much per produce)</h6>
  </div>

  <div class="field">
    <%= f.label :frequency %>
    <%= f.text_field :frequency, :placeholder => "Mondays at 6AM" %>
    <h6 class="small">(how often? weekly/time of day)</h6>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.text_field :duration, :placeholder => "1 Month" %>
    <h6 class="small">(for how long)</h6>
  </div>

  <div class="field">
    <%= f.label :price_cap %>
    $ <%= f.text_field :price_cap, :placeholder => "20.00" %>
    <h6 class="small">(total price willing to pay)</h6>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
  .small {
    margin: 0;
    padding: 0;
  }
</script>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h2>Restaurant Requests</h2>

<nav class="navbar navbar-default" role="navigation">
  <div class="nav collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
      <!--[] USED LATER FOR RESTAURANTS-->
      <li><%= link_to "Restaurant", foods_path %></li>
      <li><%= link_to "Farmer", donors_path %></li>
      <!--li>%= link_to "Pantry", recipients_path %></li-->
      <li><%= link_to "Truck Inventory", dashboard_truck_inventory_path %></li>
    </ul>
    <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
        <ul class="nav navbar-nav">
          <li><%= link_to "Matches", dashboard_matches_path %></li>
          <li><%= link_to "Archives", dashboard_archives_path %></li>
        </ul>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if !current_user.farmer_role? && current_user.pantry_role || current_user.truckdriver_role || current_user.seedforkuser_role %>
        <li><%= link_to 'New Entry', new_food_path %></li>
      <% end %>
      <!--<li>%= link_to 'Account', edit_user_registration_path %></li>-->
      <li><%= link_to edit_user_registration_path do %>
         <i class="glyphicon glyphicon-cog"></i>
      <% end %></li>
    </ul>
    
  </div>
</nav>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Amount</th>
      <th>Frequency</th>
      <th>Duration</th>
      <th>Price cap</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.food %></td>
        <td>$<%= food.amount %></td>
        <td><%= food.frequency %></td>
        <td><%= food.duration %></td>
        <td>$<%= food.price_cap %></td>
        <!--<td>%= link_to 'Show', food %></td>-->
        <td><%= link_to 'Edit', edit_food_path(food), :class => "btn btn-default" %></td>
        <td><%= link_to 'Delete', food, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @food.food %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @food.amount %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @food.frequency %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @food.duration %>
</p>

<p>
  <strong>Price cap:</strong>
  <%= @food.price_cap %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>