config/routes.rb
Rails.application.routes.draw do
  
  root to: "dashboard#index"
  devise_for :users
  
  resources :seed_fork_users
  resources :recipients
  resources :donors
  resources :foods
  
  get 'dashboard/index'
  get 'dashboard/project'
  get 'dashboard/charter'
  get 'dashboard/userstories'
  get 'dashboard/login'
  get 'dashboard/truck_inventory'
  get 'dashboard/archives'
  get 'dashboard/matches'
  

  
end

app/helpers/layout_helper.rb
module LayoutHelper
    def bootstrap_version
    #Replace with most recent version
    "3.3.7"
    end
end

app/views/layouts/application.html.erb
<!--TEMPLATE FOR EACH PAGE-->
<!DOCTYPE html>
<html>
  <head>
    <title>SeedFork Project</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">
    
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
    <%= csrf_meta_tags %>
   
    <nav class="navbar navbar-default navbar-top navbar-inverse" role="navigation">
    <!--<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">-->
    	<div class="navbar-header">
    		 
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
        </button> <a><%= link_to "Home", root_path, { :class => "navbar-brand"} %></a>
        <!--% if user_signed_in? %><!--[x]USED FOR TESTING WHO IS SIGNED IN
          </button> <a>%= link_to current_user.type_of_user, root_path, { :class => "navbar-brand"} %></a>
        % else %>
          </button> <a>%= link_to "Home", root_path, { :class => "navbar-brand"} %></a>
        % end %>-->
        
      </div>
    	
    	

    	
    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    	  <!--LEFT-->
    		<ul class="nav navbar-nav">
  				<li data-toggle="dropdown"><%= link_to "Project", dashboard_project_path %></li>
  				<ul class="dropdown-menu">
      			<li><%= link_to "Information", dashboard_project_path %></li>
      			<li><%= link_to "Charter", dashboard_charter_path %></li>
      			<li><%= link_to "User Stories", dashboard_userstories_path %></li>
  				</ul>
    			<li><%= link_to "Refrigerated Trailer", dashboard_truck_inventory_path %></li>
    		</ul>
    		
    	  <!--RIGHT-->
        <% if user_signed_in? %>
  		    <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          </nav>
        <% else %>
      		<ul class="nav navbar-nav pull-right">
            <li><%= link_to('Login', new_user_session_path) %></li>
  		    </ul>
        <% end %>
    		
    	</div>
    </nav>
  </head>
  
  <body>
    <div class="container container-fluid row col-md-12">
      
      <!--<p class="notice">%= notice %></p>-->
      <!--<p class="alert">%= alert %></p>-->
      <% if flash[:notice] -%>
        <div class = "alert alert-success alert-dismissable fade in"><%= flash[:notice] %>
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></div>
      <% end %>
      
      
      <%= yield %>
    </div>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>
    <!--<a class="scrollup" href="#">Back to top</a>-->
  </body>
  
</html>



<style>
  /*CSS: TABLE FORMAT*/
  table {
    border-collapse: collapse;
    width: 100%;
  } th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
  } tr:hover{background-color:#f5f5f5}
  
  /*body { padding-top: 100px; }*/
</style>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
<script>
  //ADD SCROLL ANIMATION
  $(document).ready(function () {
     $(window).scroll(function () {
         if ($(this).scrollTop() > 100) {
             $('.scrollup').fadeIn();
         } else {
             $('.scrollup').fadeOut();
         }
     });
     $('.scrollup').click(function () {
         $("html, body").animate({
             scrollTop: 0
         }, 600);
         return false;
     });
  });
  
  //DISABLING CNTL+U
  document.onkeydown = function(e) {
    if (e.ctrlKey && 
      (e.keyCode === 67 || 
      e.keyCode === 86 || 
      e.keyCode === 85 || 
      e.keyCode === 117)) {
      //alert('not allowed');
      return false;
    } else {
      return true;
    }
  };

  //TOGGLE LOGOUT BUTTON ON DATABASE PAGE
  function toggle() {
    var ele = document.getElementById("toggleText");
    var text = document.getElementById("displayText");
    if(ele.style.display == "block") {
      ele.style.display = "none";
    }
    else {
      ele.style.display = "block";
    }
  } 
</script>

app/views/layouts/database_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="nav collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
      <!--[] USED LATER FOR RESTAURANTS-->
      <li><%= link_to "Restaurant", foods_path %></li>
      <li><%= link_to "Farmer", donors_path %></li>
      <li><%= link_to "Pantry", recipients_path %></li>
      <li><%= link_to "Truck Inventory", dashboard_truck_inventory_path %></li>
    </ul>
    <% if user_signed_in? %>
        <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
            <ul class="nav navbar-nav">
              <li><%= link_to "Matches", dashboard_matches_path %></li>
              <li><%= link_to "Archives", dashboard_archives_path %></li>
            </ul>
          <% end %>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <!--li>%= link_to 'Account', edit_user_registration_path %></li-->
          <li><%= link_to edit_user_registration_path do %>
             <i class="glyphicon glyphicon-cog"></i>
          <% end %></li>
        </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/secondary_nav.html.erb
<!--[] NEED TO FIGURE OUT HOW TO GET THIS TO WORK WITH DATABASE PAGES-->
<nav class="navbar navbar-default" role="navigation">
  <div class="nav collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
      <!--[] USED LATER FOR RESTAURANTS-->
      <!--<li>%= link_to "Foods", foods_path %></li>-->
      <li><%= link_to "Pantry", recipients_path %></li>
            <li><%= link_to "Truck Inventory", dashboard_truck_inventory_path %></li>
        </ul>
        <% if current_user.truckdriver_role? || current_user.seedforkuser_role? %>
            <ul class="nav navbar-nav">
                <li><%= link_to "Matches", dashboard_index_path %></li>
                <li><%= link_to "Archives", dashboard_archives_path %></li>
            </ul>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if current_user.farmer_role? && !current_user.pantry_role || current_user.truckdriver_role || current_user.seedforkuser_role %>
        <li><%= link_to 'New Entry', new_donor_path %></li>
      <% end %>
        <!--<li>%= link_to 'Account', edit_user_registration_path %></li>-->
        <li><%= link_to edit_user_registration_path do %>
           <i class="glyphicon glyphicon-cog"></i>
        <% end %></li>
    </ul>
    
  </div>
</nav>